# -*- coding: utf-8 -*-
"""graphic_histogram

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zqWcdHvKlCciv2g6RSJdKonDw2ew979E
"""

from matplotlib import pyplot as plt

y = [15, 2, 5, 7, 1]

plt.hist(y)

plt.show()